--					RIGHT SESSION
USE sakila;

SHOW VARIABLES LIKE "TRANSACTION_ISOLATION";

--					READ UNCOMMITTED
--					CHANGE ISOLATION
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
--					CHECK AGAIN
SHOW VARIABLES LIKE "TRANSACTION_ISOLATION"; -- READ-UNCOMMITTED

begin;
SELECT *
FROM film 
WHERE film_id = 7;

-- ISSUE DIRTY READS

UPDATE film SET title = "Right-Session" WHERE film_id = 7;
commit;

------------------------------------------------------------

--							RIGHT SESSION
--							READ COMMITTED
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
--					CHECK AGAIN
SHOW VARIABLES LIKE "TRANSACTION_ISOLATION"; -- READ-COMMITTED

begin;
SELECT *
FROM film
WHERE film_id = 100;
commit;

---------------------------------------------------------------
--							RIGHT SESSION
--							REPEATABLE READS

SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
--					CHECK AGAIN
SHOW VARIABLES LIKE "TRANSACTION_ISOLATION"; -- REPEATABLE READ

begin;
SELECT *
FROM film
WHERE film_id = 29; -- ANTITRUST TOMATOES

SELECT *
FROM film
WHERE film_id = 1000; -- ANTITRUST TOMATOES
